name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
            # Container operations, such as postgres, are only supported on Linux runners
            # - macOS-latest
            # - windows-latest
        go:
          - "1.21"
          - "1.20"
          - "1.19"
          - "1.18"
          - "1.17"
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        uses: golangci/golangci-lint-action@v6

      - name: Prepare test database
        run: make db

      - name: Create table
        run: make table

      - name: Run test
        run: make test
